### ISSUE TITLE
Can I use touchSync instead of touch ?

### ISSUE THREAD

**Issue by cmal** [fatfisz/grunt-touch#1] opened 2017-01-19 15:37 UTC
Can I use touchSync instead of touch and how?
Thanks!

**Comment by fatfisz** [comment] 2017-01-19 20:01
Hi, I'm not sure what do you mean. If it's about using `touch.sync` instead of `touch` (which takes a callback), then sure, this would work too - but the `touch` call is wrapped in a promise anyway, so it is async.

Could you provide some details?

**Comment by cmal** [comment] 2017-01-21 03:38
Thank you for your reply.
For example, I use grunt watch to watch file changing on disk. If one file changed, grunt watch will recompile those files.
There are (complex) files that use components, those components are in other files. I want the files which depends on the component file to be recompiled when the component file changes.
So I use grunt-touch to touch the (complex) files when component file changes.
But I am afraid that the touch command has not finished (if there are many complex files to be touched) when the following commands (such as requirejs or less or something else) are triggered.
So I think to use touchSync function of node.js instead of touch function is more reliable.
I am not sure whether I am right. So please feel free to point out my error. Thank you!

**Comment by fatfisz** [comment] 2017-01-21 20:54
Now I understand :)

Short answer: you shouldn't have to worry.

Long answer: grunt tasks can run in two modes: synchronous and asynchronous. This task is using asynchronous mode, i.e. grunt is waiting until the task calls a special `done` method ([you can read more about it here](http://gruntjs.com/creating-tasks#why-doesn-t-my-asynchronous-task-complete)). So until this method is called ([it happens here](https://github.com/fatfisz/grunt-touch/blob/4766d24aa60089db46efb29372f457fd5d6855ae/lib/tasks/touch.js#L37)) no further tasks will be run.

On a side note, I have a hunch that maybe you don't really need grunt-touch - usually bundlers and such store info about all of the dependencies and they are updated accordingly no matter how complex they are. If you sent me your grunt config, maybe I could provide some more help.

**Comment by cmal** [comment] 2017-01-23 06:08
I'd have to say, Thank you very much. If you have time, would you please help me with my project's grunt config files and give me some advice? [Here](https://gist.github.com/anonymous/c1083e78a1ba6fc01ff136d28b87f6f3) is the grunt config file and [here](https://gist.github.com/anonymous/09232b42fd14e6db54afc8e2231cfed5) is my config folders.             
The `components` in [config.js](https://gist.github.com/anonymous/09232b42fd14e6db54afc8e2231cfed5#file-config-js) defined the components I mentioned above, and the `dependBy` in each `component` defines the `complex` files.

**Comment by fatfisz** [comment] 2018-06-09 14:33
Sorry, I didn't really make time to work on this, as I had a lot of other important stuff to do. I'll close this issue - feel free to reopen if the problem is still there.

**Closed as completed by fatfisz** 2018-06-09 14:33 UTC
